/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4i2gmgbspzgbdny465ov7wkuoi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dxsnvdfe4jcobny4acxvg4slqy",
    "aws_cloud_logic_custom": [
        {
            "name": "SesApi",
            "endpoint": "https://rl2e8bbrrf.execute-api.us-east-1.amazonaws.com/main",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
